<?php
require_once dirname(__DIR__) . '/includes/admin-auth.php';
require_once dirname(__DIR__) . '/includes/admin/quotes-repository.php';
grinco_admin_bootstrap();
grinco_admin_require_authentication();
$requestId = isset($_GET['id']) && ctype_digit((string) $_GET['id']) && (int) $_GET['id'] > 0 ? (int) $_GET['id'] : 0;
$quote = null; $productData = array('rows' => array(), 'rate' => null); $error = '';
try { $quote = $requestId ? grinco_quotes_find_request($requestId) : null; if ($quote) { $productData = grinco_quotes_request_products($requestId); } }
catch (PDOException $exception) { error_log('[GRINCO admin quote detail] Unable to load request.'); $error = 'La demande ne peut pas être chargée.'; }
if (!$quote && $error === '') { http_response_code(404); $error = 'La demande demandée est introuvable.'; }
$adminPageTitle = 'Détail de la demande'; $adminPageDescription = 'Détail protégé d’une demande de devis GRINCO RDC.'; $adminCurrentPage = 'demandes-devis'; $logoutCsrfToken = grinco_csrf_token('admin_logout');
include dirname(__DIR__) . '/includes/admin/head.php';
?>
<div class="admin-layout"><?php include dirname(__DIR__) . '/includes/admin/sidebar.php'; ?><div class="admin-main-shell"><?php include dirname(__DIR__) . '/includes/admin/header.php'; ?><main class="admin-content" id="admin-main-content"><div class="admin-page-heading admin-page-heading-with-action"><div><span class="admin-eyebrow">Suivi commercial</span><h1>Détail de la demande</h1><p><?php echo $quote ? 'Référence DEVIS-' . str_pad((string) $quote['id'], 6, '0', STR_PAD_LEFT) : 'Demande indisponible'; ?></p></div><a class="admin-secondary-button" href="<?php echo grinco_url_html('/admin/demandes-devis.php'); ?>"><i class="bi bi-arrow-left" aria-hidden="true"></i> Retour</a></div>
<?php if ($error !== ''): ?><div class="admin-module-alert is-error" role="alert"><?php echo grinco_admin_escape($error); ?></div><?php else: ?><section class="admin-quote-detail-grid"><article class="admin-panel"><div class="admin-panel-header"><h2>Informations client</h2></div><dl class="admin-quote-client"><div><dt>Nom</dt><dd><?php echo grinco_admin_escape($quote['nom']); ?></dd></div><div><dt>Entreprise</dt><dd><?php echo grinco_admin_escape($quote['entreprise'] === '' ? 'Non renseignée' : $quote['entreprise']); ?></dd></div><div><dt>Téléphone</dt><dd><a href="tel:<?php echo grinco_admin_escape(preg_replace('/[^0-9+]/', '', $quote['telephone'])); ?>"><?php echo grinco_admin_escape($quote['telephone']); ?></a></dd></div><div><dt>E-mail</dt><dd><?php if ($quote['email'] !== ''): ?><a href="mailto:<?php echo grinco_admin_escape($quote['email']); ?>"><?php echo grinco_admin_escape($quote['email']); ?></a><?php else: ?>Non renseigné<?php endif; ?></dd></div><div><dt>Date</dt><dd><?php echo grinco_admin_escape($quote['date_formatted']); ?></dd></div><div class="is-full"><dt>Message</dt><dd><?php echo $quote['message'] === '' ? 'Aucun message' : nl2br(grinco_admin_escape($quote['message'])); ?></dd></div></dl></article></section>
<section class="admin-table-card admin-quote-products"><div class="admin-table-toolbar"><div><h2>Produits demandés</h2><p><?php echo count($productData['rows']); ?> produit<?php echo count($productData['rows']) === 1 ? '' : 's'; ?></p></div><?php if ($productData['rate'] !== null): ?><span class="admin-panel-badge">1 USD = <?php echo grinco_admin_escape(number_format($productData['rate'], 6, ',', ' ')); ?> CNY</span><?php endif; ?></div><div class="admin-table-responsive"><table class="admin-data-table admin-quote-products-table"><thead><tr><th>N°</th><th>Image</th><th>Référence</th><th>Produit</th><th>Catégorie</th><th>Marque</th><th>Quantité</th><th>Prix unitaire USD</th><th>Prix converti CNY</th></tr></thead><tbody><?php foreach ($productData['rows'] as $index => $product): ?><tr><td data-label="N°"><?php echo $index + 1; ?></td><td data-label="Image"><span class="admin-quote-product-image"><?php if ($product['image_url'] !== ''): ?><img src="<?php echo grinco_admin_escape($product['image_url']); ?>" alt="<?php echo grinco_admin_escape($product['nom']); ?>"><?php else: ?><i class="bi bi-image" aria-hidden="true"></i><?php endif; ?></span></td><td data-label="Référence"><strong><?php echo grinco_admin_escape($product['reference']); ?></strong></td><td data-label="Produit"><?php echo grinco_admin_escape($product['nom'] . ($product['modele'] !== '' ? ' — ' . $product['modele'] : '')); ?></td><td data-label="Catégorie"><?php echo grinco_admin_escape($product['categorie_nom']); ?></td><td data-label="Marque"><?php echo grinco_admin_escape($product['marque_nom']); ?></td><td data-label="Quantité"><?php echo (int) $product['quantite']; ?></td><td data-label="Prix unitaire USD"><?php echo grinco_admin_escape($product['prix_usd_formatted']); ?></td><td data-label="Prix converti CNY"><?php echo grinco_admin_escape($product['prix_cny_formatted']); ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?></main><?php include dirname(__DIR__) . '/includes/admin/footer.php'; ?></div></div><?php include dirname(__DIR__) . '/includes/admin/scripts.php'; ?>
